SELECT * FROM animals WHERE animal_name LIKE '%mon';
SELECT * FROM animals WHERE date_of_birth >= '01-01-2016'::date AND date_of_birth <= '12-31-2019'::date;
SELECT * FROM animals WHERE neutered IN (true) AND escape_attempts < 3;
SELECT date_of_birth FROM animals WHERE animal_name IN ('Agumon', 'Pikachu');
SELECT animal_name, escape_attempts FROM animals where weight_kg > 10.5;
SELECT * FROM animals WHERE neutered IN (true);
SELECT * FROM animals WHERE animal_name != 'Gabumon';
SELECT * FROM animals WHERE weight_kg BETWEEN 10.3 AND 17.4; 
SELECT COUNT (*) FROM animals;
SELECT COUNT (*) FROM animals WHERE escape_attempts = 0;
SELECT AVG (weight_kg) FROM animals;
SELECT neutered, SUM (escape_attempts) FROM animals GROUP BY neutered;
SELECT species, MIN (weight_kg), MAX (weight_kg) FROM animals GROUP BY species;
SELECT species, AVG (escape_attempts) FROM animals WHERE date_of_birth >= '01-01-1990'::date AND date_of_birth <= '12-31-2000'::date GROUP BY species;